import Head from 'next/head'
import WebcamCapture from '../components/WebcamCapture/WebcamCapture'
import { useStateValue } from '../context/StateProvider'
import Login from '../components/Login/Login'
import { useEffect } from 'react'
import { onAuthStateChanged } from '@firebase/auth'
import { auth } from '../firebase/Firebase'
export default function Home() {
  const [{ user }, dispatch] = useStateValue();

  useEffect(() => {
    onAuthStateChanged(auth, result => {
      if (result) {
        dispatch({
          type: "LOGIN",
          payload: {
            username: result.displayName,
            profilePic: result.photoURL,
            id: result.uid
          }
        })
      }
      else {
        dispatch({
          type: "LOGOUT"
        })
      }

    })
  }, [user, dispatch])
  if (!user) {
    return <Login />
  }
  else {
    return (
      <>
        <div >
          <Head>
            <title>Snapchat</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="https://e7.pngegg.com/pngimages/865/794/png-clipart-social-media-computer-icons-snapchat-social-media-text-rectangle.png" type="image/x-icon" />
          </Head>
        </div>


        <WebcamCapture />
      </>)

  }

}
